server:
  port: 9006
spring:
  application:
    name: hrm-pager
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/hrm_page
      username: root
      password: 123456
mybatis-plus:
  mapper-locations: classpath:com/maggie/hrm/mapper/*Mapper.xml
  type-aliases-package: com.maggie.hrm.domain,com.maggie.hrm.query
